import os


class Config:

    USERNAME = ''
    PASSWORD = ''
    IMAGE_FOLDER_PATH = os.getcwd() + '/images/'
    CAPTION_LIST = ['"Quarantine Battlestation 2020. I only go out for food lol" - r/battlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"Bringing my updated, custom, his/hers Battlestation to you bros!" -r/battlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"Battlestation" -r/blender   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"I heard you guys liked jungle battlestations..." - r/battlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"Music Makin, Game Playin, Monster Slayin, Hard Workin, Battlestation." - r/battlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"Battlestation in a small apartment" - r/battlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"My Little Battlestation" - r/girlgamers   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"My WFH battlestation" - r/battlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"Roland heavy battlestation." - r/MusicBattlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"My half-marble half-wood battlestation came out nice!" -r/battlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"New to Battlestations! Years in the Making. (Dont mind the cable management.)" - r/battlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"Revamped my battlestation during quarantine! =)" - r/battlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"His and her battlestations, cat tax included." - r/battlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"My battlestation...What do you think?" - r/battlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup',
                    '"Slab of Battlestation" - r/battlestations   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ #gamer #gaming #gamingpc #mechanicalkeyboards #pcmr #pcgaming #pcsetup #pcmods #pcgamer #gaminggear #gg #gamingislife #gamingcommunity #gamingroom #videogaming #gamingchair #rtx #pcgamingsetup #rgb #gamingsetup #gamingsetups #dreamsetup']